namespace VersionBase.Libraries.Enums
{
    public enum TileImageType
    {
        empty = 0,
        badlands = 1,
        cactus = 2,
        cultivatedfarmland = 3,
        deadforest = 4,
        deadforesthills = 5,
        deadforestmountain = 6,
        deadforestmountains = 7,
        dunes = 8,
        evergreen = 9,
        evergreenhills = 10,
        evergreenmountain = 11,
        evergreenmountains = 12,
        forestedhills = 13,
        forestedmountain = 14,
        forestedmountains = 15,
        grassland = 16,
        grassyhills = 17,
        heavycactus = 18,
        heavyevergreen = 19,
        heavyforest = 20,
        hills = 21,
        jungle = 22,
        junglehills = 23,
        lightforest = 24,
        marsh = 25,
        mountain = 26,
        mountains = 27,
        reefs = 28,
        rockydesert = 29,
        sandydesert = 30,
        swamp = 31,
        volcano = 32,
        volcanodormant = 33,
    }
}
